platform :ios, '10.0'
use_frameworks!

target 'checkout_Example' do
  pod 'checkout', :path => '../'
  pod 'AirGap', :path => '../../air-gap/'
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'checkout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
